# Generated by Django 4.0.4 on 2022-06-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanagement',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmanagement',
            name='listid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.listmanagement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmanagement',
            name='conclusion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
