name: Django CI

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        cd backend/Donit
        pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        cd backend/Donit
        coverage run manage.py test
        coverage report
        coverage xml
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        name: coverage.xml # Artifact name        
        path: Donit/backend/Donit # Directory containing files to upload

  frontend_quality:

    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
    - name: Run Quality Script
      run: |
        cd frontend
        npm run quality
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
